Bump liddoc and libdparse versions
dlang-community/D-Scanner pull request #834
Opened 2021-06-02 12:11 UTC by RazvanN7

I'm trying to make dscanner use the latest versions of libddoc and libdparse to be able to recognize the AliasAssign declarations. This will unblock multiple phobos PRs such as [1]. Can someone, please provide some assistance as to what is necessary to make the phobos testing pipeline recognize the latest version of dscanner (the one with the latest versions of libddoc and libdparse).

Thanks!

[1] https://github.com/dlang/phobos/pull/8040

2021-06-02 12:26 UTC, MoonlightSentinel commented
Can someone, please provide some assistance as to what is necessary to make the phobos testing pipeline recognize the latest version of dscanner (the one with the latest versions of libddoc and libdparse).

Update `DSCANNER_HASH` [in `posix.mak`](https://github.com/dlang/phobos/blob/d875674af7b77461e946eb228bf89d17a08ab266/posix.mak#L81).

2021-06-02 13:22 UTC, WebFreak001 requested changes
doesn't update the submodule commit IDs yet

2021-06-02 13:24 UTC, WebFreak001 requested changes

2021-06-02 13:24 UTC, WebFreak001 commented on dub.json
> +    "libdparse": ">=0.18.0 <0.19.0",
0.18.0 is only needed for new syntax, but not needed for any new analyzers. As older versions still work and may be used by other tools you should keep this lowered at 0.17.0 until there are new checks actually utilizing it.

2021-06-03 11:29 UTC, RazvanN7 commented
@WebFreak001 Done.

2021-06-03 12:09 UTC, RazvanN7 commented
After bumping libddoc to the latest version I get in travis:

```
libddoc/src/ddoc/package.d(9): Error: module `sections` is in file 'ddoc/sections.d' which cannot be read
```

Looking into the repo it seems that [package.d](https://github.com/dlang-community/libddoc/blob/master/src/ddoc/package) indeed imports `ddoc.sections` which doesn't [exist](https://github.com/dlang-community/libddoc/tree/master/src/ddoc).

This [PR](https://github.com/dlang-community/libddoc/pull/54) moves `ddoc.sections` to `common/source/ddoc/sections.d` but does not update `ddoc.package.d`. I wonder why travis didn't catch this.

cc @WebFreak001

2021-06-03 12:42 UTC, WebFreak001 commented
@RazvanN7 ddoc:common defines the extra blocks: https://github.com/dlang-community/libddoc/tree/master/common/source/ddoc

As the root package depends on common unconditionally this move is fine, albeit a little harder to navigate. This seems to happen using libddoc as submodule, without DUB. I'm not sure if that's officially supported by libddoc, as it doesn't actually contain any build files to be built without dub itself. However to fix this, you need to simply add the libddoc/common/source folder to the import paths.

2021-06-03 12:58 UTC, RazvanN7 commented
@WebFreak001 Thanks! Should be good now.

2021-06-03 13:00 UTC, RazvanN7 commented
> Update DSCANNER_HASH in posix.mak.

Thanks! Once this is merged, I will open a phobos PR.

2021-06-04 10:07 UTC, RazvanN7 commented
@WebFreak001 Can we merge this?

2021-06-05 15:55 UTC, WebFreak001 approved these changes

2021-06-05 15:55 UTC, merged

2021-08-15 23:30 UTC, Moth-Tolias commented
it seems this is still a problem.

running build.bat on the current master:

```
libddoc\src\ddoc\comments.d(7): Error: module `sections` is in file 'ddoc\sections.d' which cannot be read
import path[0] = libdparse\src
import path[1] = dsymbol\src
import path[2] = containers\src
import path[3] = libddoc\src
import path[4] = stdx-allocator\source
import path[5] = C:\D\dmd2\windows\bin\..\..\src\phobos
import path[6] = C:\D\dmd2\windows\bin\..\..\src\druntime\import
```